stages:
  - test

.job:
  stage: test

  before_script:
    - cd $DIR
    - yarn install --pure-lockfile --prefer-offline --cache-folder .yarn

  script:
    - yarn ci
    - yarn build

  cache:
    key: $CI_JOB_NAME
    paths:
      - $DIR/.yarn
      - $DIR/node_modules/

include:
  - local: '/app/.gitlab-ci.yml'
  - local: '/docs/.gitlab-ci.yml'
