language: node_js

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - name: app
      node_js:
        - "10"
      script:
        - cd app
        - yarn install --pure-lockfile --prefer-offline
        - yarn ci
        - yarn build
    - name: docs
      node_js:
        - "10"
      script:
        - cd docs
        - yarn install --pure-lockfile --prefer-offline
        - yarn build

install: skip

branches:
  only:
    - master
